export const dataHukumanDisiplin = [
  {
    id: "1",
    nama: "TEGURAN LISAN",
    jenis_tingkat_hukuman_id: "R",
  },
  {
    id: "2",
    nama: "TEGURAN TERTULIS",
    jenis_tingkat_hukuman_id: "R",
  },
  {
    id: "3",
    nama: "PERNYATAAN TIDAK PUAS SECARA TERTULIS",
    jenis_tingkat_hukuman_id: "R",
  },
  {
    id: "4",
    nama: "PENUNDAAN KGB SELAMA 1 THN",
    jenis_tingkat_hukuman_id: "S",
  },
  {
    id: "5",
    nama: "PENURUNAN GAJI MAX 1 TH",
    jenis_tingkat_hukuman_id: "S",
  },
  {
    id: "6",
    nama: "PENUNDAAN GAJI MAX 1 THN",
    jenis_tingkat_hukuman_id: "S",
  },
  {
    id: "7",
    nama: "PENUNDAAN KP SELAMA 1 THN",
    jenis_tingkat_hukuman_id: "S",
  },
  {
    id: "8",
    nama: "PENURUNAN PANGKAT 1 TINGKAT 1 THN",
    jenis_tingkat_hukuman_id: "S",
  },
  {
    id: "9",
    nama: "PEMBEBASAN DARI JABATAN",
    jenis_tingkat_hukuman_id: "B",
  },
  {
    id: "10",
    nama: "PEMBERHENTIAN DENGAN HORMAT TIDAK ATAS PERMINTAAN SENDIRI",
    jenis_tingkat_hukuman_id: "B",
  },
  {
    id: "11",
    nama: "PEMBERHENTIAN TIDAK DENGAN HORMAT SEBAGAI PNS",
    jenis_tingkat_hukuman_id: "B",
  },
  {
    id: "12",
    nama: "PENGAKTIFAN HUKUMAN DISIPLIN",
    jenis_tingkat_hukuman_id: "B",
  },
  {
    id: "13",
    nama: "PEMINDAHAN DLM RANGKA PENURUNAN JABATAN 1 TINGKAT",
    jenis_tingkat_hukuman_id: "B",
  },
  {
    id: "14",
    nama: "PENURUNAN PANGKAT 1 TINGKAT 3 THN",
    jenis_tingkat_hukuman_id: "B",
  },
];

export const dataRiwayatPenghargaan = [
  {
    id: "100",
    nama: "BINTANG",
  },
  {
    id: "101",
    nama: "R.I  ADIPURNA",
  },
  {
    id: "102",
    nama: "R.I  ADIPRADANA",
  },
  {
    id: "103",
    nama: "R.I  UTAMA",
  },
  {
    id: "104",
    nama: "R.I  PRATAMA",
  },
  {
    id: "105",
    nama: "R.I  NARARYA",
  },
  {
    id: "106",
    nama: "MAHAPUTERA ADIPURNA",
  },
  {
    id: "107",
    nama: "MAHAPUTERA ADIPRADANA",
  },
  {
    id: "108",
    nama: "MAHAPUTERA UTAMA",
  },
  {
    id: "109",
    nama: "MAHAPUTERA PRATAMA",
  },
  {
    id: "110",
    nama: "MAHAPUTERA NARARYA",
  },
  {
    id: "111",
    nama: "TANDA PENGHARGAAN TRIKORA",
  },
  {
    id: "112",
    nama: "TP PEMBEBASAN IRIAN BARAT",
  },
  {
    id: "201",
    nama: "KARYA SATYA 10 TAHUN",
  },
  {
    id: "202",
    nama: "KARYA SATYA  20 TAHUN",
  },
  {
    id: "203",
    nama: "KARYA SATYA  30 TAHUN",
  },
  {
    id: "204",
    nama: "WIRA KARYA",
  },
  {
    id: "300",
    nama: "TANDA JASA LAINNYA",
  },
  {
    id: "301",
    nama: "TP  SIDHAKARYA ADHYAKSA",
  },
  {
    id: "302",
    nama: "TP  PURNABAKTI ADHYAKSA",
  },
  {
    id: "303",
    nama: "TP  DHARMA ADHYAKSA",
  },
  {
    id: "304",
    nama: "TP TELADAN  TK NASIONAL",
  },
  {
    id: "305",
    nama: "TP TELADAN  TK PROPINSI",
  },
  {
    id: "306",
    nama: "TP TELADAN TK KABUPATEN/KOTA",
  },
  {
    id: "307",
    nama: "TP PNS LUAR BIASA PRESTASINYA",
  },
  {
    id: "308",
    nama: "TP PENEMUAN BERMANFAAT BAGI NEGARA",
  },
  {
    id: "309",
    nama: "SISWA TELADAN",
  },
  {
    id: "310",
    nama: "OLIMPIADE",
  },
  {
    id: "400",
    nama: "TANDA PENGHARGAAN LAINNYA",
  },
];

export const dataAlasanHukumanDisiplin = [
  {
    id: "11EC54D9B39457B1E050640A15026590",
    nama: "TIDAK MENGUCAPKAN SUMPAH/JANJI PNS",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39557B1E050640A15026590",
    nama: "TIDAK MENGUCAPKAN SUMPAH/JANJI JABATAN",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39657B1E050640A15026590",
    nama: "TIDAK SETIA DAN TAAT SEPENUHNYA KEPADA PANCASILA, UNDANG-UNDANG DASAR NEGARA REPUPLIK INDONESIA TAHUN 1945, NEGARA KESATUAN REPUBLIK INDONESIA, DAN PEMERINTAH",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39757B1E050640A15026590",
    nama: "TIDAK MENAATI SEGALA KETENTUAN PERATURAN PERUNDANGUNDANGAN",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39857B1E050640A15026590",
    nama: "TIDAK MELAKSANAKAN TUGAS KEDINASAN YANG DIPERCAYAKAN KEPADA PNS DENGAN PENUH PENGABDIAN, KESADARAN, DAN TANGGUNG JAWAB",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39957B1E050640A15026590",
    nama: "TIDAK MENJUNJUNG TINGGI KEHORMATAN NEGARA, PEMERINTAH, DAN MARTABAT PNS",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39A57B1E050640A15026590",
    nama: "TIDAK MENGUTAMAKAN KEPENTINGAN NEGARA DARIPADA KEPENTINGAN SENDIRI, SESEORANG,DAN/ATAU GOLONGAN",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39B57B1E050640A15026590",
    nama: "TIDAK MEMEGANG RAHASIA JABATAN YANG MENURUT SIFATNYA ATAU MENURUT PERINTAH HARUS DIRAHASIAKAN",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39C57B1E050640A15026590",
    nama: "TIDAK BEKERJA DENGAN JUJUR, TERTIB, CERMAT, DAN BERSEMANGAT UNTUK KEPENTINGAN NEGARA",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39D57B1E050640A15026590",
    nama: "TIDAK MELAPORKAN DENGAN SEGERA KEPADA ATASANNYA APABILA MENGETAHUI ADA HAL YANG DAPAT MEMBAHAYAKAN ATAU MERUGIKAN NEGARA ATAU PEMERINTAH TERUTAMA DI BIDANG KEAMANAN, KEUANGAN, DAN MATERIIL",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39E57B1E050640A15026590",
    nama: "TIDAK MASUK KERJA DAN MENAATI KETENTUAN JAM KERJA",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B39F57B1E050640A15026590",
    nama: "TIDAK MENCAPAI SASARAN KERJA PEGAWAI YANG DITETAPKAN",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B3A057B1E050640A15026590",
    nama: "TIDAK MENGGUNAKAN DAN MEMELIHARA BARANG-BARANG MILIK NEGARA DENGAN SEBAIK-BAIKNYA",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B3A157B1E050640A15026590",
    nama: "TIDAK MEMBERIKAN PELAYANAN SEBAIK-BAIKNYA KEPADA MASYARAKAT",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B3A257B1E050640A15026590",
    nama: "TIDAK MEMBIMBING BAWAHAN DALAM MELAKSANAKAN TUGAS",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B3A357B1E050640A15026590",
    nama: "TIDAK MEMBERIKAN KESEMPATAN KEPADA BAWAHAN UNTUK MENGEMBANGKAN KARIER DAN;",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B3A457B1E050640A15026590",
    nama: "TIDAK MENAATI PERATURAN KEDINASAN YANG DITETAPKAN OLEH PEJABAT YANG BERWENANG.",
    keterangan: "KEWAJIBAN",
  },
  {
    id: "11EC54D9B3A557B1E050640A15026590",
    nama: "MENYALAHGUNAKAN WEWENANG",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3A657B1E050640A15026590",
    nama: "MENJADI PERANTARA UNTUK MENDAPATKAN KEUNTUNGAN PRIBADI DAN/ ATAU ORANG LAIN DENGAN MENGGUNAKAN KEWENANGAN ORANG LAIN",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3A757B1E050640A15026590",
    nama: "TANPA IZIN PEMERINTAH MENJADI PEGAWAI ATAU BEKERJA UNTUK NEGARA LAIN DAN/ ATAU LEMBAGA ATAU ORGANISASI INTERNASIONAL",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3A857B1E050640A15026590",
    nama: "BEKERJA PADA PERUSAHAAN ASING, KONSULTAN ASING, ATAU LEMBAGA SWADAYA MASYARAKAT ASING",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3A957B1E050640A15026590",
    nama: "MEMILIKI, MENJUAL, MEMBELI, MENGGADAIKAN, MENYEWAKAN, ATAU MEMINJAMKAN BARANG-BARANG BAIK BERGERAK ATAU TIDAK BERGERAK, DOKUMEN ATAU SURAT BERHARGA MILIK NEGARA SECARA TIDAK SAH",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3AA57B1E050640A15026590",
    nama: "MELAKUKAN KEGIATAN BERSAMA DENGAN ATASAN, TEMAN SEJAWAT, BAWAHAN, ATAU ORANG LAIN DI DALAM MAUPUN DI LUAR LINGKUNGAN KERJANYA DENGAN TUJUAN UNTUK KEUNTUNGAN PRIBADI, GOLONGAN, ATAU PIHAK LAIN, YANG SECARA LANGSUNG ATAU TIDAK LANGSUNG MERUGIKAN NEGARA.",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3AB57B1E050640A15026590",
    nama: "MEMBERI ATAU MENYANGGUPI AKAN MEMBERI SESUATU KEPADA SIAPAPUN BAIK SECARA LANGSUNG ATAU TIDAK LANGSUNG DAN DENGAN DALIH APAPUN UNTUK DIANGKAT DALAM JABATAN",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3AC57B1E050640A15026590",
    nama: "MENERIMA HADIAH ATAU SESUATU PEMBERIAN APA SAJA DARI SIAPAPUN JUGA YANG BERHUBUNGAN DENGAN JABATAN DAN/ ATAU PEKERJAANNYA",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3AD57B1E050640A15026590",
    nama: "BERTINDAK SEWENANG-WENANG TERHADAP BAWAHANNYA",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3AE57B1E050640A15026590",
    nama: "MELAKUKAN SUATU TINDAKAN ATAU TIDAK MELAKUKAN SUATU TINDAKAN YANG DAPAT MENGHALANGI ATAU MEMPERSULIT SALAH SATU PIHAK YANG DILAYANI SEHINGGA MENGAKIBATKAN KERUGIAN BAGI YANG DILAYANI",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3AF57B1E050640A15026590",
    nama: "MENGHALANGI BERJALANNYA TUGAS KEDINASAN",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B057B1E050640A15026590",
    nama: "IKUT SERTA SEBAGAI PELAKSANA KAMPANYE",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B157B1E050640A15026590",
    nama: "MENJADI PESERTA KAMPANYE DENGAN MENGGUNAKAN ATRIBUT PARTAI ATAU ATRIBUT PNS",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B257B1E050640A15026590",
    nama: "SEBAGAI PESERTA KAMPANYE DENGAN MENGERAHKAN PNS LAIN; DAN/ATAU",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B357B1E050640A15026590",
    nama: "SEBAGAI PESERTA KAMPANYE DENGAN MENGGUNAKAN FASILITAS NEGARA.",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B457B1E050640A15026590",
    nama: "MEMBUAT KEPUTUSAN DAN/ATAU TINDAKAN YANG MENGUNTUNGKAN ATAU MERUGIKAN SALAH SATU PASANGAN CALON SELAMA MASA KAMPANYE",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B557B1E050640A15026590",
    nama: "MENGADAKAN KEGIATAN YANG MENGARAH KEPADA KEPERPIHAKAN TERHADAP PASANGAN CALON YANG MENJADI PESERTA PEMILU SEBELUM, SELAMA, DAN SESUDAH MASA KAMPANYE MELIPUTI PERTEMUAN, AJAKAN, HIMBAUAN, SERUAN, ATAU PEMBERIAN BARANG KEPADA PNS DALAM LINGKUNGAN UNIT KERJANYA, ANGGOTA KELUARGA, DAN MASYARAKAT",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B657B1E050640A15026590",
    nama: "MEMBERIKAN DUKUNGAN KEPADA CALON ANGGOTA DEWAN PERWAKILAN DAERAH ATAU CALON KEPALA DAERAH/WAKIL KEPALA DAERAH DENGAN CARA MEMBERIKAN SURAT DUKUNGAN DISERTAI FOTO KOPI KARTU TANDA PENDUDUK ATAU SURAT KETERANGAN TANDA PENDUDUK SESUAI PERATURAN PERUNDANGUNDANGAN",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B757B1E050640A15026590",
    nama: "TERLIBAT DALAM KEGIATAN KAMPANYE UNTUK MENDUKUNG CALON KEPALA DAERAH/WAKIL KEPALA DAERAH",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B857B1E050640A15026590",
    nama: "MENGGUNAKAN FASILITAS YANG TERKAIT DENGAN JABATAN DALAM KEGIATAN KAMPANYE",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3B957B1E050640A15026590",
    nama: "MEMBUAT KEPUTUSAN DAN/ATAU TINDAKAN YANG MENGUNTUNGKAN ATAU MERUGIKAN SALAH SATU PASANGAN CALON SELAMA MASA KAMPANYE",
    keterangan: "LARANGAN",
  },
  {
    id: "11EC54D9B3BA57B1E050640A15026590",
    nama: "MENGADAKAN KEGIATAN YANG MENGARAH KEPADA KEPERPIHAKAN TERHADAP PASANGAN CALON YANG MENJADI PESERTA PEMILU SEBELUM, SELAMA, DAN SESUDAH MASA KAMPANYE MELIPUTI PERTEMUAN, AJAKAN, HIMBAUAN, SERUAN, ATAU PEMBERIAN BARANG KEPADA PNS DALAM LINGKUNGAN UNIT KERJA LINGKUNGAN UNIT KERJANYA, ANGGOTA KELUARGA, DAN MASYARAKAT.",
    keterangan: "LARANGAN",
  },
  {
    id: "A4689E6D5CA78920E050640A29032EE8",
    nama: "MELAKUKAN KEGIATAN BEPERGIAN KE LUAR DAERAH DAN/ATAU KEGIATAN MUDIK TMT 30 MARET 2020 ATAU PADA SAAT DITERBITKANNYA SE MENPAN RB NOMOR 36 TAHUN 2020 SESUAI DENGAN SE BKN NO 11/SE/IV/2020 (KATEGORI I)",
    keterangan: "LARANGAN",
  },
  {
    id: "A4689E6D5CA88920E050640A29032EE8",
    nama: "MELAKUKAN KEGIATAN BEPERGIAN KE LUAR DAERAH DAN/ATAU KEGIATAN MUDIK TMT 6 APRIL 2020 ATAU PADA SAAT DITERBITKANNYA SE MENPAN RB NOMOR 41 TAHUN 2020 SESUAI DENGAN SE BKN NO 11/SE/IV/2020 (KATEGORI II)",
    keterangan: "LARANGAN",
  },
  {
    id: "A4689E6D5CA98920E050640A29032EE8",
    nama: "MELAKUKAN KEGIATAN BEPERGIAN KE LUAR DAERAH DAN/ATAU KEGIATAN MUDIK TMT 9 APRIL 2020 ATAU PADA SAAT DITERBITKANNYA SE MENPAN RB NOMOR 46 TAHUN 2020 SESUAI DENGAN SE BKN NO 11/SE/IV/2020 (KATEGORI III)",
    keterangan: "LARANGAN",
  },
  {
    id: "C7730BC4BB20B892E050640AF2084D0C",
    nama: "MELAKUKAN TINDAK PIDANA",
    keterangan: "LARANGAN",
  },
  {
    id: "C7730BC4BB21B892E050640AF2084D0C",
    nama: "MENGGUNAKAN ATAU MENGEDARKAN NARKOBA",
    keterangan: "",
  },
  {
    id: "FE78DC78B5C5DECBE050640AF1080F68",
    nama: "TIDAK MENUNJUKKAN INTEGRITAS DAN KETELADANAN DALAM SIKAP, PERILAKU, UCAPAN, DAN TINDAKAN KEPADA SETIAP ORANG, BAIK DI DALAM MAUPUN DI LUAR KEDINASAN",
    keterangan: "KEWAJIBAN",
  },
];
